Update README.md with go v1.10 requirement
Because of the go 1.10 requirement of gopass, this project cannot be built
with go 1.9 anymore.

This is obvious when trying to build with 1.9:

```
$ go build
# github.com/camptocamp/terraform-provider-pass/vendor/github.com/gopasspw/gopass/pkg/store/secret
vendor/github.com/gopasspw/gopass/pkg/store/secret/kv.go:64:10: undefined: strings.Builder
vendor/github.com/gopasspw/gopass/pkg/store/secret/secret.go:67:10: undefined: strings.Builder
...
```

This is fixed by upgrading to 1.10.4 (current latest of 1.10).